CREATE TABLE IF NOT EXISTS "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar NOT NULL,
  "last_name" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password_hash" varchar NOT NULL,
  "role" varchar NOT NULL DEFAULT 'USER',
  "is_active" boolean DEFAULT true,
  "last_login" timestamp,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "companies" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "address" text,
  "contact" varchar,
  "telephone" varchar,
  "service" varchar,
  "logo" varchar,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "vendors" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "address" text,
  "contact_person" varchar,
  "telephone" varchar,
  "email" varchar,
  "sector" varchar,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "articles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "description" text,
  "unit_price" decimal(15,2) NOT NULL DEFAULT 0,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "purchase_requests" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "request_no" varchar UNIQUE NOT NULL,
  "request_date" date NOT NULL,
  "company_id" integer NOT NULL,
  "vendor_id" integer NOT NULL,
  "quote_number" varchar,
  "payment_terms" varchar,
  "delivery_date" date,
  "sector" varchar,
  "currency" varchar DEFAULT 'GNF',
  "subtotal" decimal(15,2) NOT NULL DEFAULT 0,
  "tax" decimal(15,2) DEFAULT 0,
  "labour_cost" decimal(15,2) DEFAULT 0,
  "total" decimal(15,2) NOT NULL DEFAULT 0,
  "instructions" text,
  "requested_by_user_id" integer NOT NULL,
  "approved_by_user_id" integer,
  "status" varchar DEFAULT 'PENDING',
  "file_url" varchar,
  "submitted_at" timestamp DEFAULT (now()),
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "purchase_request_items" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "request_id" integer NOT NULL,
  "article_id" integer,
  "article_name" varchar NOT NULL,
  "description" text,
  "quantity" decimal(10,2) NOT NULL DEFAULT 1,
  "unit_price" decimal(15,2) NOT NULL,
  "total" decimal(15,2) NOT NULL
);

ALTER TABLE "purchase_requests" ADD FOREIGN KEY ("company_id") REFERENCES "companies" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "purchase_requests" ADD FOREIGN KEY ("vendor_id") REFERENCES "vendors" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "purchase_requests" ADD FOREIGN KEY ("requested_by_user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "purchase_requests" ADD FOREIGN KEY ("approved_by_user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "purchase_request_items" ADD FOREIGN KEY ("request_id") REFERENCES "purchase_requests" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "purchase_request_items" ADD FOREIGN KEY ("article_id") REFERENCES "articles" ("id") DEFERRABLE INITIALLY IMMEDIATE;
